#!/bin/bash
# MyHostAfrica C1 Plan Django Deployment Guide
# For Ubuntu 22.04 LTS on MyHostAfrica C1 VPS

echo "🌍 MYHOSTAFRICA C1 DEPLOYMENT GUIDE"
echo "==================================="

echo ""
echo "📋 STEP 1: VPS Setup"
echo "--------------------"
echo "1. Login to MyHostAfrica control panel"
echo "2. Purchase C1 Plan VPS (1 vCPU, 2GB RAM, 30GB SSD)"
echo "3. Choose Ubuntu 22.04 LTS"
echo "4. Note your VPS IP address"
echo "5. Set root password and SSH key"

echo ""
echo "📋 STEP 2: Domain Configuration"
echo "------------------------------"
echo "In Hostinger DNS Zone Editor:"
echo "  A Record: oxiworldforexacademy.com → YOUR_VPS_IP"
echo "  A Record: www.oxiworldforexacademy.com → YOUR_VPS_IP"
echo ""
echo "Wait 5-10 minutes for DNS propagation"

echo ""
echo "📋 STEP 3: Server Setup"
echo "----------------------"
echo "SSH into your VPS:"
echo "  ssh root@YOUR_VPS_IP"
echo ""
echo "Run the C1-optimized setup script:"
echo "  curl -sSL https://raw.githubusercontent.com/DevObiChinaka/oxidane/mySaaS/myhostafrica_c1_setup.sh | bash"

echo ""
echo "📋 STEP 4: Deploy Application"
echo "----------------------------"
echo "Clone and deploy:"
echo "  su - oxidane"
echo "  cd /var/www/oxidane"
echo "  git clone https://github.com/DevObiChinaka/oxidane.git ."
echo "  bash deploy.sh"

echo ""
echo "📋 STEP 5: SSL Certificate"
echo "-------------------------"
echo "Install Certbot:"
echo "  sudo apt install certbot python3-certbot-nginx"
echo "  sudo certbot --nginx -d oxiworldforexacademy.com -d www.oxiworldforexacademy.com"

echo ""
echo "🎯 MYHOSTAFRICA C1 SPECIFIC NOTES:"
echo "=================================="
echo "• C1 Plan: 1 vCPU, 2GB RAM, 30GB SSD Storage"
echo "• 99.9% uptime SLA guarantee"
echo "• African data centers for low latency"
echo "• 24/7 technical support"
echo "• Monitor resources via MyHostAfrica dashboard"
echo "• Consider resource optimization for 2GB RAM limit"

echo ""
echo "🔧 POST-DEPLOYMENT CHECKLIST:"
echo "=============================="
echo "□ Domain DNS pointing to VPS IP"
echo "□ SSL certificates installed and working"
echo "□ All services running (gunicorn, celery, nginx)"
echo "□ Email SMTP configured"
echo "□ Payment keys configured"
echo "□ Telegram bot token set"
echo "□ Admin user created"
echo "□ Backup strategy implemented"

echo ""
echo "📊 MONITORING COMMANDS:"
echo "======================="
echo "systemctl status oxidane-gunicorn"
echo "systemctl status oxidane-celery"
echo "systemctl status nginx"
echo "tail -f /var/log/nginx/error.log"
echo "journalctl -fu oxidane-gunicorn"

echo ""
echo "✅ Ready to deploy to Hostinger VPS!"