# Generated by Django 5.0.6 on 2025-09-29 00:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('course', 'Individual Course'), ('course_bundle', 'Course Bundle'), ('signals_weekly', 'Weekly Signals'), ('signals_monthly', 'Monthly Signals'), ('signals_vip', 'VIP Signals'), ('combo_basic', 'Basic Combo (Courses + Signals)'), ('combo_premium', 'Premium Combo (All Access)')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for users', max_length=100)),
                ('description', models.TextField(help_text='Plan description for users')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='0-100', max_digits=5)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_start', models.DateTimeField(blank=True, null=True)),
                ('promotion_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this plan to users')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('features_list', models.JSONField(default=list, help_text='List of plan features for display')),
                ('call_to_action', models.CharField(default='Get Started', help_text='Button text', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SignalSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('weekly', 'Weekly Signals'), ('monthly', 'Monthly Signals'), ('vip', 'VIP Signals')], max_length=10)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('verified', 'Payment Verified'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('telegram_username', models.CharField(help_text="User's Telegram username", max_length=100)),
                ('telegram_group_name', models.CharField(blank=True, max_length=100)),
                ('telegram_status', models.CharField(choices=[('not_added', 'Not Added to Group'), ('pending_add', 'Pending Addition'), ('added', 'Added to Group'), ('removed', 'Removed from Group'), ('failed_add', 'Failed to Add')], default='not_added', max_length=15)),
                ('telegram_added_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.pricingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('course_purchase', 'Course Purchase'), ('signal_subscription', 'Signal Subscription'), ('bundle_purchase', 'Bundle Purchase'), ('refund', 'Refund')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual Payment')], max_length=10)),
                ('processor_response', models.JSONField(blank=True, help_text='Raw payment processor response', null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courseaccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signal_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.signalsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramGroupManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('add', 'Add User to Group'), ('remove', 'Remove User from Group')], max_length=10)),
                ('telegram_username', models.CharField(max_length=100)),
                ('telegram_group', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_actions_processed', to=settings.AUTH_USER_MODEL)),
                ('signal_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.signalsubscription')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
