# Generated by Django 5.2.6 on 2025-10-03 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['user', '-created_at'], name='signal_subs_user_id_00ab66_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['payment_status', '-created_at'], name='signal_subs_payment_97531f_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['plan_type', 'payment_status'], name='signal_subs_plan_ty_b1da22_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['subscription_start', 'subscription_end'], name='signal_subs_subscri_e8ccff_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['paystack_reference'], name='signal_subs_paystac_7b21fc_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['telegram_status'], name='signal_subs_telegra_ecd00a_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['updated_at'], name='signal_subs_updated_db5162_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['user', 'payment_status', '-created_at'], name='signal_subs_user_id_5f6827_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['plan_type', 'subscription_start', 'subscription_end'], name='signal_subs_plan_ty_ef0e73_idx'),
        ),
        migrations.AddIndex(
            model_name='signalsubscription',
            index=models.Index(fields=['telegram_status', 'telegram_added_at'], name='signal_subs_telegra_efaf33_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='positive_amount_paid'),
        ),
        migrations.AddConstraint(
            model_name='signalsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('subscription_end__gte', models.F('subscription_start')), ('subscription_end__isnull', True), _connector='OR'), name='valid_subscription_period'),
        ),
        migrations.AlterModelTable(
            name='signalsubscription',
            table='signal_subscriptions',
        ),
    ]
