# Generated by Django 5.2.6 on 2025-11-27 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_currency', 'target_currency'], name='exchange_ra_base_cu_46dc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['last_updated'], name='exchange_ra_last_up_6991c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base_currency', 'target_currency')},
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['category', 'is_active'], name='subscriptio_categor_552268_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['key'], name='subscriptio_key_27d5ae_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.billingprofile'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.payment'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='subscriptions.billingprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentmethod'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.billingprofile'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Features included in this plan', related_name='plans', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='New Phase 0.5 dynamic subscription plan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Plans this coupon applies to (empty = all plans)', related_name='coupons', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='associated_plans',
            field=models.ManyToManyField(blank=True, help_text='Subscription plans that grant access to this group', related_name='telegram_groups', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'event_type'], name='subscriptio_payment_d88c08_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['created_at'], name='subscriptio_created_16fb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['billing_profile', 'status'], name='subscriptio_billing_58798e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_reference'], name='subscriptio_gateway_12fb39_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['activation_status'], name='subscriptio_activat_504d13_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='subscriptio_idempot_2e9d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_active', 'sort_order'], name='subscriptio_is_acti_1f9d21_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['slug'], name='subscriptio_slug_3cc181_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['billing_period', 'is_active'], name='subscriptio_billing_aed552_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_profile', 'status'], name='subscriptio_billing_c5784f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='subscriptio_code_4fc8db_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='subscriptio_is_acti_aa582e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['-created_at'], name='subscriptio_created_f820c4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['is_active', 'sort_order'], name='subscriptio_is_acti_903763_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['chat_id'], name='subscriptio_chat_id_8e3da8_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramgroup',
            index=models.Index(fields=['group_key'], name='subscriptio_group_k_f1f385_idx'),
        ),
    ]
