# Generated by Django 5.2.6 on 2025-10-03 01:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_signalsubscription_signal_subs_user_id_00ab66_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('VIEW_SUBSCRIPTIONS_LIST', 'View Subscriptions List'), ('VIEW_SUBSCRIPTION_DETAIL', 'View Subscription Detail'), ('MODIFY_SUBSCRIPTION', 'Modify Subscription'), ('VERIFY_PAYMENT', 'Verify Payment'), ('PROCESS_REFUND', 'Process Refund'), ('EXTEND_SUBSCRIPTION', 'Extend Subscription'), ('VIEW_USERS_LIST', 'View Users List'), ('VIEW_USER_DETAIL', 'View User Detail'), ('MODIFY_USER', 'Modify User Account'), ('ACTIVATE_USER', 'Activate User'), ('DEACTIVATE_USER', 'Deactivate User'), ('TELEGRAM_ADD_USER', 'Add User to Telegram'), ('TELEGRAM_REMOVE_USER', 'Remove User from Telegram'), ('TELEGRAM_BROADCAST', 'Send Telegram Broadcast'), ('LOGIN_ADMIN', 'Admin Login'), ('LOGOUT_ADMIN', 'Admin Logout'), ('EXPORT_DATA', 'Export Data'), ('SYSTEM_CONFIG', 'System Configuration')], max_length=50)),
                ('sensitivity', models.CharField(choices=[('LOW', 'Low - General operations'), ('NORMAL', 'Normal - Standard admin actions'), ('FINANCIAL', 'Financial - Payment/subscription related'), ('HIGH', 'High - Critical security operations'), ('CRITICAL', 'Critical - System-wide changes')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed'), ('PENDING', 'Pending')], max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('target_user_id', models.UUIDField(blank=True, help_text='User affected by action', null=True)),
                ('target_subscription_id', models.UUIDField(blank=True, help_text='Subscription affected', null=True)),
                ('resource_ids', models.JSONField(blank=True, default=list, help_text='Other affected resource IDs')),
                ('action_description', models.TextField(blank=True, help_text='Human-readable action description')),
                ('changes_made', models.JSONField(blank=True, default=dict, help_text='Before/after values')),
                ('error_message', models.TextField(blank=True, help_text='Error details if action failed')),
                ('requires_retention', models.BooleanField(default=True, help_text='Must be kept for compliance')),
                ('retention_years', models.PositiveIntegerField(default=7, help_text='Years to retain this log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_action_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CacheMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_type', models.CharField(choices=[('redis', 'Redis Cache'), ('database', 'Database Query Cache'), ('api', 'API Response Cache'), ('session', 'Session Cache')], max_length=20)),
                ('cache_key_pattern', models.CharField(max_length=200)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('hit_rate_percent', models.FloatField(default=0.0)),
                ('average_retrieval_time_ms', models.FloatField(default=0.0)),
                ('cache_size_mb', models.FloatField(default=0.0)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cache_metrics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['cache_type', '-period_start'], name='cache_metri_cache_t_e258ac_idx'), models.Index(fields=['cache_key_pattern'], name='cache_metri_cache_k_143b59_idx'), models.Index(fields=['-calculated_at'], name='cache_metri_calcula_d3e653_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('VIEW_PAYMENT_DETAILS', 'View Payment Details'), ('EXPORT_FINANCIAL_DATA', 'Export Financial Data'), ('ACCESS_TRANSACTION_HISTORY', 'Access Transaction History'), ('VIEW_REVENUE_REPORTS', 'View Revenue Reports'), ('ACCESS_USER_FINANCIAL_INFO', 'Access User Financial Information')], max_length=30)),
                ('data_classification', models.CharField(default='FINANCIAL', max_length=20)),
                ('records_accessed', models.PositiveIntegerField(help_text='Number of records accessed')),
                ('data_summary', models.JSONField(default=dict, help_text='Summary of what data was accessed')),
                ('business_purpose', models.TextField(help_text='Business reason for accessing this data')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('compliance_category', models.CharField(default='PCI_DSS', max_length=20)),
                ('retention_required', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('database', 'Database Performance'), ('api', 'API Response Times'), ('telegram', 'Telegram Operations'), ('payment', 'Payment Processing'), ('admin', 'Admin Dashboard'), ('system', 'System Resources')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('throughput_per_second', models.FloatField(blank=True, null=True)),
                ('error_rate_percent', models.FloatField(blank=True, null=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, null=True)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('endpoint_path', models.CharField(blank=True, max_length=200)),
                ('user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('concurrent_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_metrics', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'performance_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', '-timestamp'], name='performance_categor_b281af_idx'), models.Index(fields=['metric_name', '-timestamp'], name='performance_metric__7ee55f_idx'), models.Index(fields=['endpoint_path', '-timestamp'], name='performance_endpoin_26d57f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregation_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_subscriptions', models.PositiveIntegerField(default=0)),
                ('new_subscriptions', models.PositiveIntegerField(default=0)),
                ('renewed_subscriptions', models.PositiveIntegerField(default=0)),
                ('cancelled_subscriptions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_subscription_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('plan_type_breakdown', models.JSONField(default=dict, help_text='Revenue and count by plan type')),
                ('verified_payments', models.PositiveIntegerField(default=0)),
                ('pending_payments', models.PositiveIntegerField(default=0)),
                ('failed_payments', models.PositiveIntegerField(default=0)),
                ('telegram_success_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('telegram_additions', models.PositiveIntegerField(default=0)),
                ('telegram_failures', models.PositiveIntegerField(default=0)),
                ('average_processing_time', models.FloatField(default=0.0, help_text='Average processing time in seconds')),
                ('admin_actions_count', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('data_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'subscription_analytics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['aggregation_period', '-period_start'], name='subscriptio_aggrega_e5993a_idx'), models.Index(fields=['period_start', 'period_end'], name='subscriptio_period__9d548e_idx'), models.Index(fields=['-calculated_at'], name='subscriptio_calcula_714fa6_idx')],
                'unique_together': {('aggregation_period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('STATUS_CHANGE', 'Payment Status Change'), ('PERIOD_EXTENSION', 'Subscription Period Extended'), ('PERIOD_SHORTENING', 'Subscription Period Shortened'), ('AMOUNT_ADJUSTMENT', 'Amount Adjusted'), ('PLAN_UPGRADE', 'Plan Upgraded'), ('PLAN_DOWNGRADE', 'Plan Downgraded'), ('TELEGRAM_UPDATE', 'Telegram Status Updated'), ('REFUND_PROCESSED', 'Refund Processed'), ('MANUAL_VERIFICATION', 'Manual Payment Verification'), ('ADMIN_NOTE_ADDED', 'Admin Note Added')], max_length=25)),
                ('field_name', models.CharField(help_text='Database field that was changed', max_length=50)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('business_justification', models.TextField(blank=True, help_text='Business reason (customer service, etc.)')),
                ('financial_impact', models.DecimalField(blank=True, decimal_places=2, help_text='Financial impact of change (positive = revenue, negative = cost)', max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('admin_action_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to='subscriptions.adminactionlog')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='subscriptions.signalsubscription')),
            ],
            options={
                'db_table': 'subscription_change_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('API_RESPONSE_TIME', 'API Response Time'), ('DATABASE_QUERY_TIME', 'Database Query Performance'), ('ADMIN_SESSION_COUNT', 'Active Admin Sessions'), ('SUBSCRIPTION_PROCESSING_TIME', 'Subscription Processing Time'), ('TELEGRAM_OPERATION_TIME', 'Telegram Operation Time'), ('CACHE_HIT_RATE', 'Cache Performance'), ('ERROR_RATE', 'System Error Rate')], max_length=30)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(help_text='ms, count, percentage, etc.', max_length=20)),
                ('endpoint_path', models.CharField(blank=True, max_length=200)),
                ('user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='system_metr_metric__25c056_idx'), models.Index(fields=['endpoint_path', '-timestamp'], name='system_metr_endpoin_2aa645_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='admin_actio_admin_u_c7b082_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='admin_actio_action__77a915_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['sensitivity', '-timestamp'], name='admin_actio_sensiti_6b8e40_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_user_id'], name='admin_actio_target__a16203_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['target_subscription_id'], name='admin_actio_target__40297a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['ip_address', '-timestamp'], name='admin_actio_ip_addr_164928_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='data_access_admin_u_9fead9_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['access_type', '-timestamp'], name='data_access_access__bf228b_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['data_classification'], name='data_access_data_cl_cde577_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchangelog',
            index=models.Index(fields=['subscription', '-timestamp'], name='subscriptio_subscri_014e32_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchangelog',
            index=models.Index(fields=['change_type', '-timestamp'], name='subscriptio_change__91067a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchangelog',
            index=models.Index(fields=['admin_action_log'], name='subscriptio_admin_a_622fba_idx'),
        ),
    ]
