# Generated by Django 5.2.6 on 2025-12-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_subscription_expiration_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent renewal (auto or manual). NULL for never renewed subscriptions.', null=True),
        ),
    ]
