# Generated by Django 5.2.6 on 2025-10-03 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_add_audit_and_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('mentorship_basic', 'Basic Mentorship'), ('mentorship_premium', 'Premium Mentorship + 1-on-1')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for users', max_length=100)),
                ('description', models.TextField(help_text='Plan description and features')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for 3-month mentorship', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], default='USD', max_length=3)),
                ('premium_content_access', models.BooleanField(default=True, help_text='Access to premium courses')),
                ('telegram_group_access', models.BooleanField(default=True, help_text='Access to mentorship Telegram group')),
                ('one_on_one_sessions', models.PositiveIntegerField(default=0, help_text='Number of 1-on-1 sessions included')),
                ('session_duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration of each 1-on-1 session')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('features_list', models.JSONField(default=list, help_text='List of plan features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('verified', 'Payment Verified'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('telegram_username', models.CharField(help_text="User's Telegram username", max_length=100)),
                ('telegram_group_name', models.CharField(default='OxiWorld_Mentorship', max_length=100)),
                ('telegram_status', models.CharField(choices=[('not_added', 'Not Added to Group'), ('pending_add', 'Pending Addition'), ('added', 'Added to Group'), ('removed', 'Removed from Group'), ('failed_add', 'Failed to Add')], default='not_added', max_length=15)),
                ('telegram_added_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_removal_scheduled', models.DateTimeField(blank=True, help_text='When to remove from group', null=True)),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('sessions_remaining', models.PositiveIntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentorship_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.mentorshipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneOnOneSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('virtual', 'Virtual Meeting'), ('physical', 'Physical Meeting'), ('phone', 'Phone Call')], default='virtual', max_length=10)),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Meet link for virtual sessions')),
                ('physical_location', models.TextField(blank=True, help_text='Address for physical meetings')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for call sessions', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=10)),
                ('session_notes', models.TextField(blank=True, help_text='Notes from the session')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('admin_notified', models.BooleanField(default=False, help_text='Has admin been notified of this session?')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mentorship_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='subscriptions.mentorshipsubscription')),
            ],
            options={
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
