# Generated by Django 5.2.6 on 2025-10-07 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_mentorshipplan_mentorshipsubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='billing_cycle',
            field=models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='plan_category',
            field=models.CharField(choices=[('mentorship', 'Mentorship'), ('signals', 'Signals'), ('vip', 'VIP')], default='signals', max_length=15),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='telegram_groups',
            field=models.JSONField(default=list, help_text="List of telegram group keys: ['mentorship', 'signals', 'vip']"),
        ),
        migrations.AddField(
            model_name='signalsubscription',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied from coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='signalsubscription',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount before coupon discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('mentorship_basic', 'Basic Mentorship'), ('signals_weekly', 'Weekly Signals'), ('signals_monthly', 'Monthly Signals'), ('signals_yearly', 'Yearly Signals'), ('vip_weekly', 'Weekly VIP'), ('vip_monthly', 'Monthly VIP'), ('vip_yearly', 'Yearly VIP'), ('course', 'Individual Course'), ('course_bundle', 'Course Bundle'), ('combo_basic', 'Basic Combo'), ('combo_premium', 'Premium Combo')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='signalsubscription',
            name='plan_type',
            field=models.CharField(choices=[('mentorship_basic', 'Basic Mentorship'), ('signals_weekly', 'Weekly Signals'), ('signals_monthly', 'Monthly Signals'), ('signals_yearly', 'Yearly Signals'), ('vip_weekly', 'Weekly VIP'), ('vip_monthly', 'Monthly VIP'), ('vip_yearly', 'Yearly VIP'), ('weekly', 'Weekly Signals (Legacy)'), ('monthly', 'Monthly Signals (Legacy)'), ('vip', 'VIP Signals (Legacy)')], max_length=25),
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Coupon code (e.g., SAVE20)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Internal name for the coupon', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the offer')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (1-100) or fixed amount', max_digits=10)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount', max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of uses (null = unlimited)', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Current usage count')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Uses per user')),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from this date')),
                ('valid_until', models.DateTimeField(help_text='Coupon valid until this date')),
                ('applicable_categories', models.JSONField(default=list, help_text="Restrict to plan categories: ['mentorship', 'signals', 'vip']")),
                ('is_active', models.BooleanField(default=True)),
                ('first_time_users_only', models.BooleanField(default=False, help_text='Only for users with no previous subscriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Restrict to specific plans (empty = all plans)', to='subscriptions.pricingplan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='signalsubscription',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.couponcode'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.couponcode')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='subscriptions.signalsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
