# Generated by Django 5.2.6 on 2025-10-25 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_add_dynamic_pricing_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.CharField(blank=True, help_text='Telegram user ID for group access', max_length=50, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram @username for reference', max_length=100)),
                ('telegram_verified', models.BooleanField(default=False, help_text='Has user verified their Telegram account?')),
                ('telegram_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, help_text='OXI-XXXX format code for Telegram verification', max_length=20, null=True, unique=True)),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('currency_preference', models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Account'), ('mobile_money', 'Mobile Money')], default='card', max_length=20)),
                ('gateway_authorization_code', models.CharField(help_text='Paystack authorization code', max_length=255, unique=True)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4)),
                ('card_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20)),
                ('card_exp_month', models.CharField(blank=True, max_length=2)),
                ('card_exp_year', models.CharField(blank=True, max_length=4)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='subscriptions.billingprofile')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('pending', 'Pending Payment')], default='pending', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('auto_renew', models.BooleanField(default=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.billingprofile')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentmethod')),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Base subscription amount', max_digits=10)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, help_text='Gateway processing fee', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total charged (amount + fee)', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_gateway', models.CharField(choices=[('paystack', 'Paystack'), ('manual', 'Manual/Admin')], default='paystack', max_length=20)),
                ('gateway_reference', models.CharField(help_text='Paystack reference/transaction ID', max_length=255, unique=True)),
                ('gateway_authorization_code', models.CharField(blank=True, help_text='For recurring payments', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('gateway_response', models.JSONField(default=dict, help_text='Full gateway response data')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.billingprofile')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentmethod')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['billing_profile', 'status'], name='subscriptio_billing_c5784f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date'], name='subscriptio_end_dat_60694b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['billing_profile', 'status'], name='subscriptio_billing_58798e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_reference'], name='subscriptio_gateway_12fb39_idx'),
        ),
    ]
