# Generated by Django 5.2.6 on 2025-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_billingprofile_paymentmethod_subscription_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipsubscription',
            name='mentorship_plan',
        ),
        migrations.RemoveField(
            model_name='mentorshipsubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oneononesession',
            name='mentorship_subscription',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='telegram_groups',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Subscription duration in days (null for mentorship/lifetime access)', null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='gives_course_access',
            field=models.BooleanField(default=False, help_text='Grants access to premium courses (mentorship only)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='gives_signals_access',
            field=models.BooleanField(default=False, help_text='Grants access to trading signals (signals plans only)'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='telegram_group_key',
            field=models.CharField(blank=True, help_text="Telegram group identifier: 'mentorship', 'signals', or 'vip'", max_length=50),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='billing_cycle',
            field=models.CharField(choices=[('one_time', 'One Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_category',
            field=models.CharField(choices=[('mentorship', 'Mentorship'), ('signals', 'Signals')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(choices=[('mentorship', 'Mentorship Program'), ('signals_weekly', 'Weekly Signals'), ('signals_monthly', 'Monthly Signals'), ('vip_monthly', 'VIP Signals')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='signalsubscription',
            name='plan_type',
            field=models.CharField(choices=[('mentorship', 'Mentorship Program'), ('signals_weekly', 'Weekly Signals'), ('signals_monthly', 'Monthly Signals'), ('vip_monthly', 'VIP Signals')], max_length=25),
        ),
        migrations.DeleteModel(
            name='MentorshipPlan',
        ),
        migrations.DeleteModel(
            name='MentorshipSubscription',
        ),
        migrations.DeleteModel(
            name='OneOnOneSession',
        ),
    ]
