# Generated by Django 5.2.6 on 2025-11-01 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_simplify_pricing_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text="Unique identifier for programmatic access (e.g., 'view_premium_signals')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Display name shown to users (e.g., 'View Premium Signals')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this feature provides')),
                ('category', models.CharField(choices=[('signals', 'Signals & Trading'), ('telegram', 'Telegram Groups'), ('courses', 'Courses & Education'), ('support', 'Support & Mentorship'), ('api', 'API & Integrations'), ('analytics', 'Analytics & Reporting')], help_text='Feature category for organization', max_length=50)),
                ('icon', models.CharField(default='✨', help_text='Emoji icon for visual representation', max_length=10)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this feature is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['category', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='subscriptio_categor_552268_idx'), models.Index(fields=['key'], name='subscriptio_key_27d5ae_idx')],
            },
        ),
    ]
