# Generated by Django 5.2.6 on 2025-11-01 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_add_feature_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in USD', max_digits=10)),
                ('billing_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('trial_days', models.IntegerField(default=0, help_text='Number of days for free trial (0 = no trial)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for purchase')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this plan on pricing page')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order on pricing page (lower = first)')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Plan limits (e.g., {"max_signals": 100, "max_courses": 5})')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this plan', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, help_text='Features included in this plan', related_name='plans', to='subscriptions.feature')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'base_price'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='subscriptio_is_acti_1f9d21_idx'), models.Index(fields=['slug'], name='subscriptio_slug_3cc181_idx'), models.Index(fields=['billing_period', 'is_active'], name='subscriptio_billing_aed552_idx')],
            },
        ),
    ]
