# Generated by Django 5.2.6 on 2025-11-01 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_add_subscription_plan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='applicable_plans',
        ),
        migrations.RemoveField(
            model_name='couponcode',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Coupon code (e.g., SAVE20, SUMMER2024)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount in USD', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the coupon becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the coupon expires (null = never expires)', null=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum total uses (null = unlimited)', null=True)),
                ('max_uses_per_user', models.IntegerField(default=1, help_text='Maximum uses per user')),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active')),
                ('description', models.TextField(blank=True, help_text='Internal description of the coupon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
                ('plans', models.ManyToManyField(blank=True, help_text='Plans this coupon applies to (empty = all plans)', related_name='coupons', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='signalsubscription',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.coupon'),
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='subscriptio_code_4fc8db_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='subscriptio_is_acti_aa582e_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['-created_at'], name='subscriptio_created_f820c4_idx'),
        ),
        migrations.DeleteModel(
            name='CouponCode',
        ),
    ]
