# Generated by Django 5.2.6 on 2025-11-01 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_replace_old_coupon_with_new'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Referral code (e.g., JOHN2024, REFMARY)', max_length=50, unique=True)),
                ('referrer_discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], default='percentage', help_text='Type of discount for the referrer', max_length=20)),
                ('referrer_discount_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount value for referrer', max_digits=10)),
                ('referee_discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], default='percentage', help_text='Type of discount for the referee', max_length=20)),
                ('referee_discount_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount value for referee', max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum total uses (null = unlimited)', null=True)),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the referral code becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the referral code expires (null = never expires)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this referral code is currently active')),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.ForeignKey(help_text='User who owns this referral code', on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='subscriptio_code_a6babe_idx'), models.Index(fields=['referrer'], name='subscriptio_referre_791173_idx'), models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='subscriptio_is_acti_2f68ca_idx'), models.Index(fields=['-created_at'], name='subscriptio_created_a22a1d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('referrer_discount_value__gte', 0)), name='referrer_discount_value_positive'), models.CheckConstraint(condition=models.Q(('referee_discount_value__gte', 0)), name='referee_discount_value_positive'), models.CheckConstraint(condition=models.Q(('current_uses__gte', 0)), name='referral_current_uses_positive')],
            },
        ),
    ]
