# Generated by Django 5.2.6 on 2025-11-01 19:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_create_referral_code_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_amount', models.DecimalField(decimal_places=2, help_text='Original subscription amount', max_digits=10)),
                ('referrer_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount given to referrer', max_digits=10)),
                ('referee_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount given to referee', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Commission percentage (0-100)', max_digits=5)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission amount earned by referrer', max_digits=10)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission amount already paid', max_digits=10)),
                ('commission_currency', models.CharField(default='USD', help_text='Currency for commission', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', help_text='Payment status of commission', max_length=20)),
                ('conversion_date', models.DateTimeField(auto_now_add=True, help_text='When the referral conversion occurred')),
                ('paid_date', models.DateTimeField(blank=True, help_text='When commission was paid', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this referral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee', models.ForeignKey(help_text='User who was referred (used the code)', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(help_text='The referral code that was used', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='subscriptions.referralcode')),
                ('referrer', models.ForeignKey(help_text='User who referred (owner of the code)', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription created from this referral', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='subscriptions.signalsubscription')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-conversion_date'],
                'indexes': [models.Index(fields=['referrer', '-conversion_date'], name='subscriptio_referre_fb12b0_idx'), models.Index(fields=['referee'], name='subscriptio_referee_9e89c0_idx'), models.Index(fields=['status'], name='subscriptio_status_37d9ba_idx'), models.Index(fields=['-conversion_date'], name='subscriptio_convers_969b91_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subscription_amount__gte', 0)), name='referral_subscription_amount_positive'), models.CheckConstraint(condition=models.Q(('referrer_discount_amount__gte', 0)), name='referral_referrer_discount_positive'), models.CheckConstraint(condition=models.Q(('referee_discount_amount__gte', 0)), name='referral_referee_discount_positive'), models.CheckConstraint(condition=models.Q(('commission_earned__gte', 0)), name='referral_commission_earned_positive'), models.CheckConstraint(condition=models.Q(('commission_paid__gte', 0)), name='referral_commission_paid_positive'), models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='referral_commission_rate_valid')],
            },
        ),
    ]
