# Generated by Django 5.2.6 on 2025-11-01 20:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_create_referral_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Discount percentage (typically 5%)', max_digits=5)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this credit has been redeemed')),
                ('earned_date', models.DateTimeField(auto_now_add=True, help_text='When this credit was earned')),
                ('used_date', models.DateTimeField(blank=True, help_text='When this credit was redeemed', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this credit expires (null = never expires)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this credit')),
            ],
            options={
                'verbose_name': 'Referral Credit',
                'verbose_name_plural': 'Referral Credits',
                'ordering': ['-earned_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='referral_subscription_amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='referral_referrer_discount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='referral_commission_earned_positive',
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='referral_commission_paid_positive',
        ),
        migrations.RemoveConstraint(
            model_name='referral',
            name='referral_commission_rate_valid',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='commission_currency',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='commission_earned',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='commission_paid',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer_discount_amount',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='subscription_amount',
        ),
        migrations.AddField(
            model_name='referral',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, help_text='When this referral was cancelled (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='referral',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount paid after discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original subscription price before discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='referee_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Discount percentage applied to referee (default 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referee_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount given to referee in currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', help_text='Status of this referral', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='referral_original_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('final_amount__gte', 0)), name='referral_final_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.CheckConstraint(condition=models.Q(('referee_discount_percent__gte', 0), ('referee_discount_percent__lte', 100)), name='referral_discount_percent_valid'),
        ),
        migrations.AddField(
            model_name='referralcredit',
            name='earned_from_referral',
            field=models.OneToOneField(help_text='The referral that triggered this credit', on_delete=django.db.models.deletion.CASCADE, related_name='generated_credit', to='subscriptions.referral'),
        ),
        migrations.AddField(
            model_name='referralcredit',
            name='used_on_subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription where this credit was applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_credit_used', to='subscriptions.signalsubscription'),
        ),
        migrations.AddField(
            model_name='referralcredit',
            name='user',
            field=models.ForeignKey(help_text='User who earned this discount credit', on_delete=django.db.models.deletion.CASCADE, related_name='referral_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='referralcredit',
            index=models.Index(fields=['user', 'is_used'], name='subscriptio_user_id_89fe18_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcredit',
            index=models.Index(fields=['user', '-earned_date'], name='subscriptio_user_id_f960e9_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcredit',
            index=models.Index(fields=['is_used'], name='subscriptio_is_used_05d8d9_idx'),
        ),
    ]
