# Generated by Django 5.2.6 on 2025-11-01 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_refactor_referral_to_discount_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription created from this referral (NEW billing system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='referralcredit',
            name='used_on_subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription where this credit was applied (NEW billing system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_credit_used', to='subscriptions.subscription'),
        ),
    ]
