# Generated by Django 5.2.6 on 2025-11-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_update_referral_to_new_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', help_text='Telegram bot API token from @BotFather', max_length=500)),
                ('bot_username', models.CharField(blank=True, default='', help_text='Bot username (e.g., @OxidaneBot)', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable Telegram integration')),
                ('is_connected', models.BooleanField(default=False, help_text='Whether the bot is currently connected')),
                ('connection_error', models.TextField(blank=True, default='', help_text='Last connection error message')),
                ('last_health_check', models.DateTimeField(blank=True, help_text='Last time bot connection was verified', null=True)),
                ('auto_add_enabled', models.BooleanField(default=True, help_text='Automatically add users to groups on subscription')),
                ('auto_remove_enabled', models.BooleanField(default=True, help_text='Automatically remove users from groups when subscription expires')),
                ('welcome_message', models.TextField(blank=True, default='', help_text='Welcome message sent to users when added to groups')),
                ('removal_message', models.TextField(blank=True, default='', help_text='Message sent when users are removed from groups')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts for failed operations')),
                ('retry_delay_seconds', models.PositiveIntegerField(default=300, help_text='Delay in seconds between retry attempts')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=30, help_text='Maximum Telegram API calls per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'verbose_name_plural': 'Telegram Configuration',
            },
        ),
    ]
