# Generated by Django 5.2.6 on 2025-11-01 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_create_telegram_configuration_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name for the Telegram group', max_length=200, unique=True)),
                ('chat_id', models.CharField(help_text="Telegram chat ID (must start with '-', e.g., -1001234567890)", max_length=50, unique=True)),
                ('group_key', models.SlugField(help_text='Internal identifier for the group (lowercase, no spaces)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of the group's purpose and content")),
                ('invite_link', models.URLField(blank=True, help_text='Telegram invite link for public groups')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is currently active')),
                ('is_private', models.BooleanField(default=False, help_text='Private groups require bot invitation; public groups use invite links')),
                ('member_count', models.PositiveIntegerField(default=0, help_text='Current number of members in the group')),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Maximum allowed members (null = unlimited)', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time member count was synced from Telegram', null=True)),
                ('auto_add_enabled', models.BooleanField(default=True, help_text='Automatically add users when they subscribe')),
                ('auto_remove_enabled', models.BooleanField(default=True, help_text='Automatically remove users when subscription expires')),
                ('welcome_message', models.TextField(blank=True, help_text='Custom welcome message for new members (supports {{user_name}}, {{group_name}} variables)')),
                ('removal_message', models.TextField(blank=True, help_text='Custom message when removing members (supports {{user_name}}, {{group_name}} variables)')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Enable notifications for group events')),
                ('can_send_messages', models.BooleanField(default=True, help_text='Bot can send messages in this group')),
                ('can_add_users', models.BooleanField(default=True, help_text='Bot can add users to this group')),
                ('can_remove_users', models.BooleanField(default=True, help_text='Bot can remove users from this group')),
                ('can_pin_messages', models.BooleanField(default=False, help_text='Bot can pin messages in this group')),
                ('can_delete_messages', models.BooleanField(default=False, help_text='Bot can delete messages in this group')),
                ('is_admin', models.BooleanField(default=False, help_text='Bot has admin privileges in this group')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying groups (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_plans', models.ManyToManyField(blank=True, help_text='Subscription plans that grant access to this group', related_name='telegram_groups', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='subscriptio_is_acti_903763_idx'), models.Index(fields=['chat_id'], name='subscriptio_chat_id_8e3da8_idx'), models.Index(fields=['group_key'], name='subscriptio_group_k_f1f385_idx')],
            },
        ),
    ]
