# Generated by Django 5.2.6 on 2025-11-01 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_create_telegram_group_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paystack_public_key', models.CharField(blank=True, default='', help_text='Paystack public/publishable key (pk_test_... or pk_live_...)', max_length=500)),
                ('paystack_secret_key', models.CharField(blank=True, default='', help_text='Paystack secret key (sk_test_... or sk_live_...)', max_length=500)),
                ('paystack_webhook_secret', models.CharField(blank=True, default='', help_text='Paystack webhook secret for signature verification', max_length=500)),
                ('paystack_webhook_url', models.URLField(blank=True, help_text='Auto-generated webhook URL for Paystack')),
                ('paystack_enabled', models.BooleanField(default=True, help_text='Enable Paystack as a payment option')),
                ('stripe_publishable_key', models.CharField(blank=True, default='', help_text='Stripe publishable key (pk_test_... or pk_live_...)', max_length=500)),
                ('stripe_secret_key', models.CharField(blank=True, default='', help_text='Stripe secret key (sk_test_... or sk_live_...)', max_length=500)),
                ('stripe_webhook_secret', models.CharField(blank=True, default='', help_text='Stripe webhook secret (whsec_...)', max_length=500)),
                ('stripe_webhook_url', models.URLField(blank=True, help_text='Auto-generated webhook URL for Stripe')),
                ('stripe_enabled', models.BooleanField(default=False, help_text='Enable Stripe as a payment option')),
                ('primary_provider', models.CharField(choices=[('paystack', 'Paystack (Nigerian Market)'), ('stripe', 'Stripe (International)')], default='paystack', help_text='Primary payment provider to use', max_length=20)),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use test API keys (sandbox mode)')),
                ('supported_currencies', models.JSONField(blank=True, default=list, help_text='List of supported currency codes (e.g., ["NGN", "USD", "GBP"])')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Configuration',
                'verbose_name_plural': 'Payment Configuration',
            },
        ),
    ]
