# Generated by Django 5.2.6 on 2025-11-01 23:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_create_payment_configuration_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(blank=True, default='', help_text='SMTP server hostname (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='SMTP server port (25, 587 for TLS, 465 for SSL)')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (port 587)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (port 465)')),
                ('smtp_username', models.EmailField(blank=True, default='', help_text='SMTP username (usually an email address)', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', help_text='SMTP password (will be encrypted in Phase 2)', max_length=500)),
                ('from_email', models.EmailField(blank=True, default='', help_text='Default "From" email address', max_length=255)),
                ('from_name', models.CharField(default='OxiWorld', help_text='Default "From" name', max_length=200)),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable email sending')),
                ('is_connected', models.BooleanField(default=False, help_text='Last connection test was successful')),
                ('connection_error', models.TextField(blank=True, help_text='Last connection error message', max_length=500, null=True)),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Last connection test timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
