# Generated by Django 5.2.6 on 2025-11-01 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_create_email_configuration_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(help_text='Base currency code (e.g., USD)', max_length=3)),
                ('target_currency', models.CharField(help_text='Target currency code (e.g., NGN)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from base to target currency', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this rate was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
                'ordering': ['base_currency', 'target_currency'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency'], name='exchange_ra_base_cu_46dc7f_idx'), models.Index(fields=['last_updated'], name='exchange_ra_last_up_6991c4_idx')],
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
