# Generated by Django 5.2.6 on 2025-11-01 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_create_exchange_rate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional subscription metadata (source, campaign, notes, etc.)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='New Phase 0.5 dynamic subscription plan', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='referral',
            field=models.ForeignKey(blank=True, help_text='Referral that led to this subscription (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_subscriptions', to='subscriptions.referral'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription created from this referral (NEW billing system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_entry', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Old pricing plan (Phase 0.4)', null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.pricingplan'),
        ),
    ]
