# Generated by Django 5.2.6 on 2025-11-04 00:10
"""
Migration to drop deprecated Phase 0.4 model tables.

This migration removes the following deprecated tables:
- subscriptions_pricingplan (replaced by subscriptions_subscriptionplan)
- subscriptions_signalsubscription (replaced by subscriptions_subscription)
- subscriptions_paymenttransaction (will be recreated in Phase 0.5.17+)
- subscriptions_telegramgroupmanagement (replaced by subscriptions_telegramgroup)

IMPORTANT: Backup your database before running this migration!
This operation is IRREVERSIBLE and will permanently delete data.

The new Phase 0.5 models should already have data migrated from Phase 0.4.
If you need to preserve old data, export it before applying this migration.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_update_subscription_model_phase_0_5'),
    ]

    operations = [
        # Drop deprecated Phase 0.4 tables
        migrations.RunSQL(
            sql="""
                -- Drop old PricingPlan table (replaced by SubscriptionPlan)
                DROP TABLE IF EXISTS subscriptions_pricingplan CASCADE;
                
                -- Drop old SignalSubscription table (replaced by Subscription)
                DROP TABLE IF EXISTS subscriptions_signalsubscription CASCADE;
                
                -- Drop old PaymentTransaction table (will be recreated in Phase 0.5.17+)
                DROP TABLE IF EXISTS subscriptions_paymenttransaction CASCADE;
                
                -- Drop old TelegramGroupManagement table (replaced by TelegramGroup)
                DROP TABLE IF EXISTS subscriptions_telegramgroupmanagement CASCADE;
            """,
            reverse_sql="""
                -- This migration is intentionally irreversible.
                -- Rolling back would require recreating the old table structure
                -- and restoring data from a backup.
                -- If you need to rollback, restore from database backup.
            """
        ),
    ]
