# Generated by Django 5.2.6 on 2025-11-27
# Replacement for broken 0023 migration - no operations needed

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_phase04_cleanup_complete'),
    ]

    operations = [
        # No operations - cleanup already done in previous migrations
    ]
