# Generated by Django 5.2.6 on 2025-11-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_phase04_cleanup_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactionlog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='subscriptionchangelog',
            name='admin_action_log',
        ),
        migrations.DeleteModel(
            name='CacheMetrics',
        ),
        migrations.RemoveField(
            model_name='dataaccesslog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='course_access',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='signal_subscription',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='PerformanceMetrics',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pricing_plan',
        ),
        migrations.RemoveField(
            model_name='signalsubscription',
            name='pricing_plan',
        ),
        migrations.RemoveField(
            model_name='signalsubscription',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='signalsubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegramgroupmanagement',
            name='signal_subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionchangelog',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionAnalytics',
        ),
        migrations.DeleteModel(
            name='SystemMetrics',
        ),
        migrations.RemoveField(
            model_name='telegramgroupmanagement',
            name='processed_by',
        ),
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
        migrations.DeleteModel(
            name='DataAccessLog',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.DeleteModel(
            name='SignalSubscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionChangeLog',
        ),
        migrations.DeleteModel(
            name='TelegramGroupManagement',
        ),
    ]
