# Generated by Django 5.2.6 on 2025-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_remove_adminactionlog_admin_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, help_text='Paystack Plan Code for this plan', max_length=255, null=True),
        ),
    ]
