# Generated by Django 5.2.6 on 2025-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_remove_subscriptionplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='smtp_username',
            field=models.CharField(blank=True, default='', help_text='SMTP username (email address or API key)', max_length=255),
        ),
    ]
