# Generated by Django 5.2.6 on 2025-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_change_smtp_username_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='from_name',
            field=models.CharField(blank=True, default='OxiWorld', help_text='Default "From" name', max_length=200),
        ),
    ]
