# Generated by Django 5.2.6 on 2025-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_allow_blank_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Whether this subscription is currently in trial period'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When trial period ends (null after trial converts to paid)', null=True),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='verification_code',
            field=models.CharField(blank=True, help_text='6-character alphanumeric code for Telegram verification', max_length=20, null=True, unique=True),
        ),
    ]
