# Generated by Django 5.2.6 on 2025-11-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_add_trial_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='trial_end_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='trial_days',
        ),
    ]
