# Generated by Django 5.2.6 on 2025-11-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_remove_trial_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(default='chart-bar', help_text="Icon name for visual representation (e.g., 'chart-bar', 'lightning-bolt')", max_length=50),
        ),
    ]
