# Generated by Django 5.2.6 on 2025-11-12 21:40

from django.db import migrations


def convert_emoji_icons_to_names(apps, schema_editor):
    """Convert emoji icons to icon names"""
    Feature = apps.get_model('subscriptions', 'Feature')
    
    # Emoji to icon name mapping
    emoji_to_icon = {
        '✨': 'sparkles',
        '📊': 'chart-bar',
        '💬': 'chat',
        '📚': 'book-open',
        '🎓': 'academic-cap',
        '💰': 'currency-dollar',
        '🔒': 'lock-closed',
        '🎯': 'chart-bar',  # Target -> Chart
        '⚡': 'lightning-bolt',
        '🚀': 'rocket',
        '💡': 'light-bulb',
        '🛠️': 'cog',
        '📈': 'trending-up',
        '🔔': 'bell',
        '👥': 'users',
        '📱': 'device-mobile',
    }
    
    # Update all features
    for feature in Feature.objects.all():
        if feature.icon in emoji_to_icon:
            feature.icon = emoji_to_icon[feature.icon]
            feature.save(update_fields=['icon'])
        elif len(feature.icon) <= 2:  # Likely an emoji
            # Default to chart-bar for any unknown emoji
            feature.icon = 'chart-bar'
            feature.save(update_fields=['icon'])


def reverse_conversion(apps, schema_editor):
    """Reverse: Convert icon names back to emojis"""
    Feature = apps.get_model('subscriptions', 'Feature')
    
    # Icon name to emoji mapping (reverse)
    icon_to_emoji = {
        'sparkles': '✨',
        'chart-bar': '📊',
        'chat': '💬',
        'book-open': '📚',
        'academic-cap': '🎓',
        'currency-dollar': '💰',
        'lock-closed': '🔒',
        'lightning-bolt': '⚡',
        'rocket': '🚀',
        'light-bulb': '💡',
        'cog': '🛠️',
        'trending-up': '📈',
        'bell': '🔔',
        'users': '👥',
        'device-mobile': '📱',
    }
    
    for feature in Feature.objects.all():
        if feature.icon in icon_to_emoji:
            feature.icon = icon_to_emoji[feature.icon]
            feature.save(update_fields=['icon'])


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0029_update_feature_icon_field'),
    ]

    operations = [
        migrations.RunPython(convert_emoji_icons_to_names, reverse_conversion),
    ]
