# Generated by Django 5.2.6 on 2025-11-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_convert_emoji_to_icon_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='referralcredit',
            name='earned_from_referral',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='referralcredit',
            name='used_on_subscription',
        ),
        migrations.RemoveField(
            model_name='referralcredit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
        migrations.DeleteModel(
            name='ReferralCredit',
        ),
    ]
