# Generated by Django 5.2.6 on 2025-11-17 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0031_remove_subscription_referral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Payment Created'), ('payment_processing', 'Payment Processing'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('activation_started', 'Activation Started'), ('activation_completed', 'Activation Completed'), ('activation_failed', 'Activation Failed'), ('webhook_received', 'Webhook Received'), ('reconciliation_attempted', 'Reconciliation Attempted')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Additional event details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When subscription was successfully activated', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='activation_attempts',
            field=models.IntegerField(default=0, help_text='Number of times activation was attempted'),
        ),
        migrations.AddField(
            model_name='payment',
            name='activation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of subscription activation (separate from payment processing)', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Unique key to prevent duplicate payments', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_activation_error',
            field=models.TextField(blank=True, help_text='Last error encountered during activation'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['activation_status'], name='subscriptio_activat_504d13_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['idempotency_key'], name='subscriptio_idempot_2e9d0f_idx'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscriptions.payment'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'event_type'], name='subscriptio_payment_d88c08_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['created_at'], name='subscriptio_created_16fb7a_idx'),
        ),
    ]
