# Generated by Django 5.2.6 on 2025-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0032_paymentevent_payment_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='telegram_verification_error',
            field=models.TextField(blank=True, help_text='Last verification error message (cleared on success)', null=True),
        ),
    ]
