# Generated by Django 5.2.6 on 2025-10-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chat_id', models.CharField(help_text='Telegram chat ID (e.g., -1002920074390)', max_length=50, unique=True)),
                ('group_key', models.SlugField(help_text="Internal key for code reference (e.g., 'premium_signals')", unique=True)),
                ('access_level', models.CharField(choices=[('all', 'All Paid Subscribers'), ('weekly', 'Weekly+ Subscribers'), ('monthly', 'Monthly+ Subscribers'), ('vip', 'VIP Only'), ('mentorship', 'Mentorship Members')], default='monthly', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_add_users', models.BooleanField(default=True, help_text='Automatically add verified users to this group')),
                ('auto_remove_expired', models.BooleanField(default=True, help_text='Automatically remove users when subscription expires')),
                ('welcome_message_enabled', models.BooleanField(default=True)),
                ('welcome_message_template', models.TextField(blank=True, help_text='Template for welcome message. Use {{user_name}}, {{plan_type}} variables.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('member_count', models.PositiveIntegerField(default=0, editable=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Group',
                'verbose_name_plural': 'Telegram Groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('platform', 'Platform Settings'), ('email', 'Email Configuration'), ('telegram', 'Telegram Integration'), ('courses', 'Course Settings'), ('security', 'User & Security'), ('notifications', 'Notifications'), ('system', 'System & Maintenance'), ('payment', 'Payment Gateway'), ('legal', 'Legal & Compliance')], db_index=True, max_length=20)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.JSONField(help_text='Setting value stored as JSON for flexibility')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON Object'), ('text', 'Long Text'), ('email', 'Email Address'), ('url', 'URL'), ('color', 'Color Code')], default='string', max_length=20)),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether this value is encrypted (for passwords, API keys)')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether to hide this value in UI (show asterisks)')),
                ('label', models.CharField(help_text='Human-readable label for UI', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Help text explaining this setting')),
                ('default_value', models.JSONField(blank=True, help_text='Default value if not set', null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text="JSON object with validation rules: {'min': 0, 'max': 100, 'pattern': '^[a-z]+$'}", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires a server restart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SettingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('change_reason', models.TextField(blank=True, help_text='Optional reason for this change')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_changes', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='settings_app.platformsetting')),
            ],
            options={
                'verbose_name': 'Setting Change Log',
                'verbose_name_plural': 'Setting Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SettingsBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('settings_data', models.JSONField(help_text='JSON snapshot of all settings at backup time')),
                ('telegram_groups_data', models.JSONField(blank=True, help_text='JSON snapshot of Telegram groups', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_backups', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings Backup',
                'verbose_name_plural': 'Settings Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='platformsetting',
            index=models.Index(fields=['category', 'key'], name='settings_ap_categor_b338cb_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsetting',
            index=models.Index(fields=['category', 'is_active'], name='settings_ap_categor_62ee4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformsetting',
            unique_together={('category', 'key')},
        ),
        migrations.AddIndex(
            model_name='settingchangelog',
            index=models.Index(fields=['setting', '-changed_at'], name='settings_ap_setting_29ac4f_idx'),
        ),
        migrations.AddIndex(
            model_name='settingchangelog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='settings_ap_changed_0c940f_idx'),
        ),
    ]
