# Generated by Django 5.2.6 on 2025-11-27 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingchangelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingchangelog',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='settings_app.platformsetting'),
        ),
        migrations.AddField(
            model_name='settingsbackup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settingsbackup',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformsetting',
            index=models.Index(fields=['category', 'key'], name='settings_ap_categor_b338cb_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsetting',
            index=models.Index(fields=['category', 'is_active'], name='settings_ap_categor_62ee4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformsetting',
            unique_together={('category', 'key')},
        ),
        migrations.AddIndex(
            model_name='settingchangelog',
            index=models.Index(fields=['setting', '-changed_at'], name='settings_ap_setting_29ac4f_idx'),
        ),
        migrations.AddIndex(
            model_name='settingchangelog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='settings_ap_changed_0c940f_idx'),
        ),
    ]
