# Generated by Django 5.2.6 on 2025-11-27 23:13

import courses.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Full course title for display (max 120 chars)', max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for course cards', max_length=300)),
                ('course_type', models.CharField(choices=[('free', 'Free Course'), ('premium', 'Premium Course')], default='free', max_length=10)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('access_type', models.CharField(choices=[('free', 'Free - Available to all users'), ('plan_based', 'Plan-based - Requires specific subscription plan')], default='free', help_text='How users can access this course', max_length=20)),
                ('meta_title', models.CharField(blank=True, help_text='SEO optimized title (max 60 chars) - auto-generated if empty', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('trailer_video_url', models.URLField(blank=True, help_text='YouTube trailer video URL')),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Estimated duration in minutes')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='When access expires. Null = lifetime access', null=True)),
                ('access_granted_by', models.CharField(choices=[('subscription', 'Subscription Plan'), ('admin', 'Admin Grant'), ('coupon', 'Coupon/Promotion')], default='admin', help_text='How this access was granted', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment ID or transaction reference', max_length=255)),
                ('download_enabled', models.BooleanField(default=True, help_text='Can download lessons for offline viewing')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Access',
                'verbose_name_plural': 'Course Access Records',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.PositiveIntegerField(default=0, help_text='0-100')),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total time in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('video_source', models.CharField(choices=[('upload', 'Uploaded Video'), ('youtube', 'YouTube Video'), ('vimeo', 'Vimeo Video')], default='upload', max_length=10)),
                ('video_file', models.FileField(blank=True, help_text='Max 500MB. Formats: MP4, MOV, AVI, WebM. For longer videos, use YouTube or Vimeo.', null=True, upload_to='lesson_videos/', validators=[courses.validators.validate_video_file_size, courses.validators.validate_video_file_type])),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL')),
                ('youtube_video_id', models.CharField(blank=True, max_length=20)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False, help_text='Can be viewed by non-premium users')),
                ('lesson_notes', models.TextField(blank=True, help_text='PDF notes or additional text content')),
                ('downloadable_resources', models.FileField(blank=True, help_text='Max 50MB. Formats: PDF, Office docs, images, ZIP archives.', null=True, upload_to='lesson_resources/', validators=[courses.validators.validate_resource_file_size, courses.validators.validate_resource_file_type])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.PositiveIntegerField(default=0, help_text='0-100')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this token was used')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
