# Generated by Django 5.2.6 on 2025-11-27 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_plans',
            field=models.ManyToManyField(blank=True, help_text='Subscription plans that grant access to this course (for plan_based access)', related_name='courses', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Plan that granted access (if access_granted_by=subscription)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
    ]
