# Generated by Django 5.2.6 on 2025-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO optimized title (max 60 chars) - auto-generated if empty', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Full course title for display (max 120 chars)', max_length=120),
        ),
    ]
