# Generated by Django 5.2.6 on 2025-11-27 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Course category for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoaccesslog',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='videoaccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['user', 'access_granted_by'], name='courses_cou_user_id_685a62_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['subscription_plan'], name='courses_cou_subscri_de44d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseaccess',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='videoaccesslog',
            index=models.Index(fields=['access_token'], name='courses_vid_access__471056_idx'),
        ),
        migrations.AddIndex(
            model_name='videoaccesslog',
            index=models.Index(fields=['user', 'lesson'], name='courses_vid_user_id_c564b3_idx'),
        ),
        migrations.AddIndex(
            model_name='videoaccesslog',
            index=models.Index(fields=['expires_at'], name='courses_vid_expires_5060d9_idx'),
        ),
    ]
