# Generated by Django 5.2.6 on 2025-11-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecategory_course_category'),
        ('subscriptions', '0026_allow_blank_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free - Available to all users'), ('plan_based', 'Plan-based - Requires specific subscription plan'), ('direct_purchase', 'Direct Purchase - One-time payment')], default='free', help_text='How users can access this course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='direct_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for direct purchase (for direct_purchase access type)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='required_plans',
            field=models.ManyToManyField(blank=True, help_text='Subscription plans that grant access to this course (for plan_based access)', related_name='courses', to='subscriptions.subscriptionplan'),
        ),
    ]
