# Generated by Django 5.2.6 on 2025-11-09 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_subscription_fields'),
        ('subscriptions', '0026_allow_blank_from_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseaccess',
            options={'verbose_name': 'Course Access', 'verbose_name_plural': 'Course Access Records'},
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='access_granted_by',
            field=models.CharField(choices=[('subscription', 'Subscription Plan'), ('direct_purchase', 'Direct Purchase'), ('admin', 'Admin Grant'), ('coupon', 'Coupon/Promotion')], default='direct_purchase', help_text='How this access was granted', max_length=20),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment ID or transaction reference', max_length=255),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Plan that granted access (if access_granted_by=subscription)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='courseaccess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, help_text='When access expires. Null = lifetime access', null=True),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['user', 'access_granted_by'], name='courses_cou_user_id_685a62_idx'),
        ),
        migrations.AddIndex(
            model_name='courseaccess',
            index=models.Index(fields=['subscription_plan'], name='courses_cou_subscri_de44d8_idx'),
        ),
    ]
