# Generated by Django 5.2.6 on 2025-11-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_populate_access_granted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='direct_purchase_price',
        ),
        migrations.AlterField(
            model_name='course',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free - Available to all users'), ('plan_based', 'Plan-based - Requires specific subscription plan')], default='free', help_text='How users can access this course', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseaccess',
            name='access_granted_by',
            field=models.CharField(choices=[('subscription', 'Subscription Plan'), ('admin', 'Admin Grant'), ('coupon', 'Coupon/Promotion')], default='admin', help_text='How this access was granted', max_length=20),
        ),
    ]
