# Generated by Django 5.2.6 on 2025-11-12 23:04

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_direct_purchase_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='downloadable_resources',
            field=models.FileField(blank=True, help_text='Max 50MB. Formats: PDF, Office docs, images, ZIP archives.', null=True, upload_to='lesson_resources/', validators=[courses.validators.validate_resource_file_size, courses.validators.validate_resource_file_type]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Max 500MB. Formats: MP4, MOV, AVI, WebM. For longer videos, use YouTube or Vimeo.', null=True, upload_to='lesson_videos/', validators=[courses.validators.validate_video_file_size, courses.validators.validate_video_file_type]),
        ),
    ]
