# Generated by Django 5.2.6 on 2025-11-27 23:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('email_verification_expires', models.DateTimeField(blank=True, null=True)),
                ('email_verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('email_verification_otp_expires', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=100, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password_reset_otp_expires', models.DateTimeField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, help_text='Telegram user ID for bot operations', null=True, unique=True)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial Period'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('none', 'No Subscription')], db_index=True, default='none', help_text='Current subscription status', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, help_text='When the current subscription period started', null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, db_index=True, help_text='When the current subscription period ends', null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='When the trial period ends (if in trial)', null=True)),
                ('trial_used', models.BooleanField(default=False, help_text='Whether user has already used their trial period')),
                ('usage_stats', models.JSONField(blank=True, default=dict, help_text='Track feature usage (e.g., {"signals_viewed": 10, "courses_enrolled": 2})')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_plan', models.ForeignKey(blank=True, help_text='Current active subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_users', to='subscriptions.subscriptionplan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for identification', max_length=100)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('subscription_success', 'Subscription Success'), ('subscription_expiry', 'Subscription Expiry Warning'), ('subscription_renewal', 'Subscription Renewal'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('renewal_reminder', 'Renewal Reminder'), ('telegram_added', 'Telegram Group Added'), ('telegram_removed', 'Telegram Group Removed'), ('signin_notification', 'Sign-in Notification'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('custom', 'Custom Template')], help_text='Type of email template', max_length=50)),
                ('subject_template', models.CharField(help_text='Email subject with variables like {{user.name}}', max_length=200)),
                ('html_content', models.TextField(help_text='HTML email content with variables')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version (optional)')),
                ('description', models.TextField(blank=True, help_text='Description of when this template is used')),
                ('available_variables', models.JSONField(default=dict, help_text='Available variables for this template')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('is_system_email', models.BooleanField(default=False, help_text='System-critical email that cannot be deleted or deactivated')),
                ('from_email', models.EmailField(blank=True, help_text='Override default from email', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='From name for email', max_length=100)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Number of emails sent using this template')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this template was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('template_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('variables_used', models.JSONField(default=dict, help_text='Variables that were substituted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='users.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_login', models.BooleanField(default=True, help_text='Notify on login')),
                ('course_updates', models.BooleanField(default=True, help_text='Notify about course updates')),
                ('subscription_renewal', models.BooleanField(default=True, help_text='Notify before subscription renewal')),
                ('promotional_emails', models.BooleanField(default=False, help_text='Receive promotional emails')),
                ('signal_alerts', models.BooleanField(default=True, help_text='Receive trading signal notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(help_text='Email of admin (preserved even if admin deleted)', max_length=254)),
                ('action', models.CharField(choices=[('activate', 'Activated User'), ('deactivate', 'Deactivated User'), ('verify_email', 'Verified Email'), ('make_staff', 'Granted Staff Privileges'), ('remove_staff', 'Removed Staff Privileges'), ('delete', 'Deleted User'), ('bulk_activate', 'Bulk Activated Users'), ('bulk_deactivate', 'Bulk Deactivated Users'), ('bulk_verify', 'Bulk Verified Emails'), ('impersonate', 'Impersonated User'), ('send_email', 'Sent Email to User'), ('update_subscription', 'Updated Subscription'), ('export_users', 'Exported Users to CSV'), ('other', 'Other Action')], max_length=30)),
                ('action_display', models.CharField(help_text='Human-readable action description', max_length=200)),
                ('target_email', models.EmailField(blank=True, help_text='Email of affected user (preserved even if user deleted)', max_length=254)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action (e.g., reason, previous values, affected count)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User who was affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='users_admin_admin_u_3823f1_idx'), models.Index(fields=['target_user', '-created_at'], name='users_admin_target__8aa36c_idx'), models.Index(fields=['action', '-created_at'], name='users_admin_action_30dde2_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
