# Generated by Django 5.2.6 on 2025-10-03 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verification_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for identification', max_length=100)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('subscription_success', 'Subscription Success'), ('subscription_expiry', 'Subscription Expiry Warning'), ('subscription_renewal', 'Subscription Renewal'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('renewal_reminder', 'Renewal Reminder'), ('telegram_added', 'Telegram Group Added'), ('telegram_removed', 'Telegram Group Removed'), ('signin_notification', 'Sign-in Notification'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('custom', 'Custom Template')], help_text='Type of email template', max_length=50)),
                ('subject_template', models.CharField(help_text='Email subject with variables like {{user.name}}', max_length=200)),
                ('html_content', models.TextField(help_text='HTML email content with variables')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version (optional)')),
                ('description', models.TextField(blank=True, help_text='Description of when this template is used')),
                ('available_variables', models.JSONField(default=dict, help_text='Available variables for this template')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('from_email', models.EmailField(blank=True, help_text='Override default from email', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='From name for email', max_length=100)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Number of emails sent using this template')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this template was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('template_type', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('variables_used', models.JSONField(default=dict, help_text='Variables that were substituted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='users.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
