# Generated by Django 5.2.6 on 2025-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailtemplate_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID for bot operations', null=True, unique=True),
        ),
    ]
