# Generated by Django 5.2.6 on 2025-10-24 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_telegram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_login', models.BooleanField(default=True, help_text='Notify on login')),
                ('course_updates', models.BooleanField(default=True, help_text='Notify about course updates')),
                ('subscription_renewal', models.BooleanField(default=True, help_text='Notify before subscription renewal')),
                ('promotional_emails', models.BooleanField(default=False, help_text='Receive promotional emails')),
                ('signal_alerts', models.BooleanField(default=True, help_text='Receive trading signal notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
