# Generated by Django 5.2.6 on 2025-11-09 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_allow_blank_from_name'),
        ('users', '0006_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.ForeignKey(blank=True, help_text='Current active subscription plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribed_users', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the current subscription period ends', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, help_text='When the current subscription period started', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial Period'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('none', 'No Subscription')], db_index=True, default='none', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends (if in trial)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='Whether user has already used their trial period'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Track feature usage (e.g., {"signals_viewed": 10, "courses_enrolled": 2})'),
        ),
    ]
