# Generated by Django 5.2.6 on 2025-11-13 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_email', models.EmailField(help_text='Email of admin (preserved even if admin deleted)', max_length=254)),
                ('action', models.CharField(choices=[('activate', 'Activated User'), ('deactivate', 'Deactivated User'), ('verify_email', 'Verified Email'), ('make_staff', 'Granted Staff Privileges'), ('remove_staff', 'Removed Staff Privileges'), ('delete', 'Deleted User'), ('bulk_activate', 'Bulk Activated Users'), ('bulk_deactivate', 'Bulk Deactivated Users'), ('bulk_verify', 'Bulk Verified Emails'), ('impersonate', 'Impersonated User'), ('send_email', 'Sent Email to User'), ('update_subscription', 'Updated Subscription'), ('other', 'Other Action')], max_length=30)),
                ('action_display', models.CharField(help_text='Human-readable action description', max_length=200)),
                ('target_email', models.EmailField(blank=True, help_text='Email of affected user (preserved even if user deleted)', max_length=254)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action (e.g., reason, previous values, affected count)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='User who was affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='users_admin_admin_u_3823f1_idx'), models.Index(fields=['target_user', '-created_at'], name='users_admin_target__8aa36c_idx'), models.Index(fields=['action', '-created_at'], name='users_admin_action_30dde2_idx')],
            },
        ),
    ]
