# Generated by Django 5.2.6 on 2025-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adminaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_system_email',
            field=models.BooleanField(default=False, help_text='System-critical email that cannot be deleted or deactivated'),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('activate', 'Activated User'), ('deactivate', 'Deactivated User'), ('verify_email', 'Verified Email'), ('make_staff', 'Granted Staff Privileges'), ('remove_staff', 'Removed Staff Privileges'), ('delete', 'Deleted User'), ('bulk_activate', 'Bulk Activated Users'), ('bulk_deactivate', 'Bulk Deactivated Users'), ('bulk_verify', 'Bulk Verified Emails'), ('impersonate', 'Impersonated User'), ('send_email', 'Sent Email to User'), ('update_subscription', 'Updated Subscription'), ('export_users', 'Exported Users to CSV'), ('other', 'Other Action')], max_length=30),
        ),
    ]
